### PR TITLE
Feature/functionify

### PR DESCRIPTION
**Pull request by albertochiappa**
- Update .gitignore
- Move the evolution equation to a different module and remove the unused time parameter
- Update main.py

### CODE REVIEW

**Comment by AlexEMG** [comment]
Thanks, @albertochiappa 

I'd suggest: 
- [ ] expand docs in functions 
- [ ] add parameter definitions in functions 

Compare: scipy style, e.g. https://github.com/scipy/scipy/blob/master/scipy/integrate/_odepack_py.py#L28

**Review by LucZot — APPROVED** [review]

**Comment by albertochiappa** [comment]
I have added the docstring in Numpy/Scipy style.

**Review by LucZot — APPROVED** [review]

**Review by AlexEMG — APPROVED** [review]
Thanks, also added the type.

**Comment by AlexEMG** [comment]
(I'm squashing and merging!)

**Pull request merged**
